name: Publish on GitHub

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run publish-win
        env:
          GH_TOKEN: ${{ secrets.github_token }}
